# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
import_types = ["diesel::sql_types::*", "postgis_diesel::sql_types::*"]
filter = { except_tables = ["spatial_ref_sys"] }

[migrations_directory]
dir = "migrations"
